// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bcacpp
Rcpp::NumericVector bcacpp(Rcpp::NumericMatrix exp, Rcpp::IntegerVector tfs, Rcpp::NumericVector par);
RcppExport SEXP bireg_bcacpp(SEXP expSEXP, SEXP tfsSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type exp(expSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tfs(tfsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(bcacpp(exp, tfs, par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"bireg_bcacpp", (DL_FUNC) &bireg_bcacpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bireg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
