# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcacpp <- function(exp, tfs, par) {
    .Call('bireg_bcacpp', PACKAGE = 'bireg', exp, tfs, par)
}

